services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    
  # FQCM Basis (Vendor & Extension Name
  DerMatthesFrauHofer\ExtExtendttaddress\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'
  